import assert from 'node:assert/strict'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { build, artifactPath, chromium } from './runtime.mjs'
import { buildZhLocaleIsland } from './localeIsland.mjs'
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const bundle = artifactPath(root, 'richPaste/richPaste.js')
await build({ entryPoints: [path.join(root,'test/browser/richPasteFixture.ts')], bundle:true, outfile:bundle, format:'iife', loader:{'.svg':'file'}, assetNames:'assets/[name]' })
const { islandHtml } = await buildZhLocaleIsland(root)
const browser = await chromium.launch({ headless: true, channel: process.env.VSIDIAN_TEST_BROWSER_CHANNEL || undefined })
try {
  const context = await browser.newContext({ permissions:['clipboard-read','clipboard-write'], viewport:{width:900,height:560} })
  const page = await context.newPage()
  await page.route('http://localhost/**', async route => {
    const name=path.basename(new URL(route.request().url()).pathname)
    if(name.endsWith('.svg')) return route.fulfill({path:artifactPath(root,'richPaste/assets',name),contentType:'image/svg+xml'})
    return route.fulfill({contentType:'text/html; charset=utf-8',body:`<html><head><meta charset="utf-8"></head><body style="--vscode-editor-background:#fff;--vscode-editor-foreground:#222;--vscode-editorWidget-background:#f8f8f8;--vscode-editorWidget-foreground:#222">${islandHtml}<div id="app"></div></body></html>`})
  })
  await page.goto('http://localhost/')
  await page.addStyleTag({path:bundle.replace(/\.js$/,'.css')})
  await page.addScriptTag({path:bundle})
  const editor=page.locator('.cm-content'), dialog=page.locator('[role=dialog]')
  async function write(text,html) {
    await page.evaluate(async ({text,html})=>{
      const data={}
      if(text!==undefined)data['text/plain']=new Blob([text],{type:'text/plain'})
      if(html!==undefined)data['text/html']=new Blob([html],{type:'text/html'})
      await navigator.clipboard.write([new ClipboardItem(data)])
    },{text,html})
  }
  async function selectAll() { await editor.click(); await page.keyboard.press('Control+A') }
  async function waitText(text) { await page.waitForFunction(text=>window.text()===text,text) }
  await write('新内容','<b style="font-weight:normal"><span style="font-weight:700">新内容</span></b>')
  await selectAll();await page.keyboard.press('Control+V');await dialog.waitFor()
  assert.equal(await page.evaluate(()=>window.text()),'原文')
  assert.notEqual(await dialog.evaluate(el=>getComputedStyle(el).backgroundColor),'rgba(0, 0, 0, 0)')
  assert.equal(await page.locator('[data-paste-choice=keep]').evaluate(el=>document.activeElement===el),true)
  await dialog.screenshot({path:artifactPath(root,'richPaste/dialog-light.png')})
  await page.keyboard.press('Tab')
  assert.equal(await page.locator('[data-paste-choice=plain]').evaluate(el=>document.activeElement===el),true)
  await page.keyboard.press('Shift+Tab');await page.keyboard.press('Enter');await waitText('**新内容**')
  await page.waitForFunction(()=>document.querySelector('.vsidian-toast')?.textContent.includes('已保留'))
  assert.equal(await editor.evaluate(el=>document.activeElement===el),true)
  console.log('[PASS] native CtrlV、Docs形态fixture、询问绘制、局部Tab/Enter、格式编辑与成功toast')
  await page.waitForTimeout(2800)
  await write('取消文本','<b>取消文本</b>');await selectAll();await page.keyboard.press('Control+V');await dialog.waitFor()
  await page.locator('[data-paste-remember]').check();await page.keyboard.press('Escape')
  await dialog.waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>window.text()),'**新内容**')
  assert.equal(await page.evaluate(()=>window.sent().filter(m=>m.kind==='paste.preferences.set').length),0)
  await page.evaluate(()=>window.settings({'editor.pasteAskBefore':false}))
  await write('菜单文本','<em>菜单文本</em>');await selectAll();await editor.click({button:'right'})
  await page.locator('[data-vsidian-command=paste]').click();await waitText('*菜单文本*')
  console.log('[PASS] Esc勾选不保存；菜单读取HTML与native路径语义一致')
  await page.waitForTimeout(2800)
  await page.evaluate(()=>window.settings({'editor.pasteAskBefore':true}))
  await write('纯文本','<b>纯文本</b>');await selectAll();await page.keyboard.press('Control+V');await dialog.waitFor()
  await page.locator('[data-paste-remember]').check();await page.locator('[data-paste-choice=plain]').click();await waitText('纯文本')
  await page.evaluate(()=>window.openSettings())
  const total=page.locator('[data-setting-key="editor.pastePreserveFormatting"]'),ask=page.locator('[data-setting-key="editor.pasteAskBefore"]')
  await total.waitFor();assert.equal(await total.isChecked(),false);assert.equal(await ask.isChecked(),false);assert.equal(await ask.isDisabled(),true)
  await total.check();await ask.check()
  assert.equal(await ask.isDisabled(),false)
  await page.evaluate(()=>window.openSettings())
  assert.equal(await total.isChecked(),true);assert.equal(await ask.isChecked(),true)
  console.log('[PASS] 本次仅文本+记忆、设置重新打开回显、灰化保值与恢复询问')
  // 关闭新开设置页面DOM，让正文重新可见；真实外部软件留人工验收。
  await page.evaluate(()=>window.closeSettings())
  await page.evaluate(()=>window.settings({'editor.pasteAskBefore':false}))
  await write('*字面Markdown*','<p>*字面Markdown*</p>');await selectAll();await page.keyboard.press('Control+V');await waitText('*字面Markdown*')
  assert.equal(await dialog.count(),0)
  await write('本地图','<img src="https://file+.vscode-resource.vscode-cdn.net/d:/notes/a.png" alt="本地图">')
  await selectAll();await page.keyboard.press('Control+V');await waitText('本地图')
  assert.equal(await dialog.count(),0)
  await write('图片文字','<p>图片文字<img src="https://example.com/a.png"></p>')
  await selectAll();await page.keyboard.press('Control+Shift+V');await waitText('图片文字')
  await page.waitForFunction(()=>document.querySelector('.vsidian-toast')?.textContent.includes('未粘贴图片'))
  console.log('[PASS] 普通包装不询问、资源代理图alt降级、HTML图纯文本入口warning')
  await page.waitForTimeout(4200)
  await page.evaluate(()=>window.replace('```js\nold\n```'))
  await page.evaluate(()=>window.controller.getView().dispatch({selection:{anchor:6,head:9}}))
  await write('code','<b>code</b>');await editor.focus();await page.keyboard.press('Control+V');await waitText('```js\ncode\n```')
  assert.equal(await dialog.count(),0)
  console.log('[PASS] 代码上下文优先纯文本')
} finally { await browser.close() }
